#!/bin/sh

sxhkd &

# CHANGEME with your own wallpaper dir
wallpaper_dir="~/Pictures/walls"

export dotfile_dir="$(dirname "$(readlink -f "$0")")"

feh --randomize --bg-fill ${wallpaper_dir}/*
wmname LG3D

${dotfile_dir}/set_screen.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
