#!/bin/sh

sxhkd &

bspc config normal_border_color "#131313"
bspc config focused_border_color "#05e3ab"
bspc config presel_feedback_color "#da0f7a"

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding         25
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config focus_by_distance    	false
bspc config history_aware_focus  	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	false
bspc config click_to_focus 		false
bspc config adaptive raise 		true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config center_pseudo_tiled  true

bspc config initial_polarity second_child

compton --config ~/.config/compton/compton.conf &

# CHANGEME with your own wallpaper dir
wallpaper_dir="/home/tang/Pictures/walls"

export dotfile_dir="$(dirname "$(readlink -f "$0")")"
feh --randomize --bg-fill $wallpaper_dir/* &
wmname LG3D &

$dotfile_dir/set_screen.sh &
~/.config/lemonbar/run_lemonbar.sh &
